config/routes.rb
Rails.application.routes.draw do
  use_doorkeeper

  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }

  root 'questions#index'

  concern :votable do
    member do
      patch :like
      patch :dislike
      delete :indifferent
    end
  end

  concern :commentable do
    resources :comments, only: :create
  end

  resources :questions, except: :index, concerns: [:votable, :commentable], shallow: true do
    resources :answers, only: [:create, :update, :destroy], concerns: [:votable, :commentable] do
      patch :best, on: :member
    end

    resources :subscriptions, only: [:create, :destroy]
  end

  resources :authorizations, only: [:new, :create] do
    get 'confirm/:token', action: :confirm, on: :member, as: :confirm
  end

  get '/search' => 'search#index', as: :search

  namespace :api do
    namespace :v1 do
      resources :profiles, only: :index do
        get :me, on: :collection
      end

      resources :questions, only: [:index, :show, :create] do
        resources :answers, only: [:index, :show, :create]
      end
    end
  end
end

app/models/question.rb
# == Schema Information
#
# Table name: questions
#
#  id         :integer          not null, primary key
#  title      :string           not null
#  content    :text             not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  user_id    :integer
#

class Question < ActiveRecord::Base
  include Attachable, Votable, Commentable

  belongs_to :user

  has_many :answers, dependent: :destroy
  has_many :subscriptions, dependent: :destroy
  has_many :subscribers, through: :subscriptions

  validates :user_id, :title, :content, presence: true

  scope :digest, -> { where created_at: (Time.parse('00:00:00') - 1.day)..(Time.parse('23:59:59') - 1.day) }

  after_commit :subscribe_to_question, on: :create

  private

  def subscribe_to_question
    subscriptions.create(user: user)
  end
end

app/controllers/api/v1/questions_controller.rb
class Api::V1::QuestionsController < Api::V1::BaseController
  load_and_authorize_resource

  skip_load_resource only: :create

  def index
    respond_with @questions
  end

  def show
    respond_with @question
  end

  def create
    respond_with current_resource_owner.questions.create(question_params)
  end

  private

  def question_params
    params.require(:question).permit(:title, :content)
  end
end

app/controllers/questions_controller.rb
# == Schema Information
#
# Table name: questions
#
#  id         :integer          not null, primary key
#  title      :string           not null
#  content    :text             not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  user_id    :integer
#

class QuestionsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :build_question, only: :create

  after_action :publish_question, only: :create

  load_and_authorize_resource

  include Voted

  before_action :set_subscription, only: [:show, :update]

  respond_to :js, only: :update

  def index
    respond_with @questions
  end

  def show
    gon.question_id = @question.id
    respond_with @question
  end

  def new
    respond_with @question
  end

  def create
    @question.save
    respond_with @question
  end

  def update
    @question.update(question_params)
    respond_with @question
  end

  def destroy
    respond_with(@question.destroy, location: root_url)
  end

  private

  def build_question
    @question = current_user.questions.build(question_params)
  end

  def set_subscription
    @subscription = current_user.subscriptions.find_by(question: @question) if current_user
  end

  def publish_question
    PrivatePub.publish_to '/questions', JSON.parse_nil(render_to_string 'show.json') if @question.valid?
  end

  def question_params
    params.require(:question).permit(:title, :content, attachments_attributes: [:id, :file, :_destroy])
  end
end

app/views/questions/_edit_form.html.haml
= form_for @question, html: { class: 'form', style: 'display: none;' }, remote: true do |f|
  .form__field
    = f.label :title
    = f.text_field :title, class: 'form__input'
  .form__field
    = f.label :content
    = f.text_area :content, class: 'form__input'
  = f.fields_for :attachments do |attachment|
    = render 'layouts/attachment_fields', f: attachment
  .actions
    = f.submit 'Update', class: 'button button_green'

app/views/questions/_question.html.haml
- cache [question, current_user] do
  = content_tag_for :div, question do
    - if can?(:create, Subscription) && subscription.nil?
      = link_to 'Subscribe to the question', question_subscriptions_path(question), method: :post, remote: true, class: 'subscribe-link'
    - if can? :destroy, subscription
      = link_to 'Unsubscribe to the question', subscription_path(subscription), method: :delete, remote: true, class: 'subscribe-link'
    = vote_for question
    %h1<= question.title
    %p<= question.content
    = render question.attachments
    .comments
      = render question.comments
    = render partial: 'comments/form', locals: { commentable: question }
    - if can? :update, question
      = render 'questions/edit_form'
      .actions
        = button_tag 'Edit', class: 'button button_orange button_question-edit', type: 'button'
        = link_to 'Delete', question, method: :delete, class: 'button button_red'

app/views/questions/index.html.haml
= render 'layouts/search'
%h1 Questions
- cache collection_cache_key_for(:question, current_user) do
  - @questions.each do |question|
    .question
      %h2<= question.title
      .actions
        = link_to 'Delete', question, method: :delete, class: 'button button_red' if can? :destroy, question
        = link_to 'More', question, class: 'button button_blue'
= subscribe_to '/questions'

app/views/questions/new.html.haml
%h1 New question
= form_for @question, html: { class: 'form' } do |f|
  .form__field
    = f.label :title
    = f.text_field :title, class: 'form__input'
  .form__field
    = f.label :content
    = f.text_area :content, class: 'form__input'
  = f.fields_for :attachments, @question.attachments.build do |attachment|
    = render 'layouts/attachment_fields', f: attachment
  .actions
    = link_to_add_association 'Add attachment', f, :attachments, partial: 'layouts/attachment_fields', class: 'button button_blue'
    = f.submit 'Save', class: 'button button_green'

app/views/questions/show.html.haml
= render partial: @question, locals: { subscription: @subscription }
.answers
  = render @question.answers
- if can? :create, Answer
  = form_for [@question, @question.answers.build], remote: true, data: { type: :json } , html: { class: 'form' } do |f|
    .form__field
      = f.label :content
      = f.text_area :content, class: 'form__input'
    .actions
      = link_to_add_association 'Add attachment', f, :attachments, partial: 'layouts/attachment_fields', class: 'button button_blue'
      = f.submit 'Reply', class: 'button button_green'
- else
  .actions
    = link_to 'Sign in to answer', new_user_session_path, rel: 'nofollow', class: 'button button_green'
= subscribe_to "/questions/#{@question.id}/answers"
= subscribe_to '/comments'

app/views/questions/update.js.erb
<%= render 'layouts/notifications' %>

(function() {
    <% if @question.errors.present? %>
        $('form#edit_question_<%= @question.id %>').replaceWith('<%= j render 'questions/edit_form' %>');
        $('form#edit_question_<%= @question.id %>').show();
    <% else %>
        $('#question_<%= @question.id %>').replaceWith('<%= j render partial: @question, locals: { subscription: @subscription } %>');
    <% end %>
})();