config/routes.rb
Rails.application.routes.draw do
  use_doorkeeper

  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }

  root 'questions#index'

  concern :votable do
    member do
      patch :like
      patch :dislike
      delete :indifferent
    end
  end

  concern :commentable do
    resources :comments, only: :create
  end

  resources :questions, except: :index, concerns: [:votable, :commentable], shallow: true do
    resources :answers, only: [:create, :update, :destroy], concerns: [:votable, :commentable] do
      patch :best, on: :member
    end

    resources :subscriptions, only: [:create, :destroy]
  end

  resources :authorizations, only: [:new, :create] do
    get 'confirm/:token', action: :confirm, on: :member, as: :confirm
  end

  get '/search' => 'search#index', as: :search

  namespace :api do
    namespace :v1 do
      resources :profiles, only: :index do
        get :me, on: :collection
      end

      resources :questions, only: [:index, :show, :create] do
        resources :answers, only: [:index, :show, :create]
      end
    end
  end
end

app/models/answer.rb
# == Schema Information
#
# Table name: answers
#
#  id          :integer          not null, primary key
#  question_id :integer          not null
#  content     :text             not null
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  user_id     :integer
#  best        :boolean          default(FALSE), not null
#

class Answer < ActiveRecord::Base
  include Attachable, Votable, Commentable

  default_scope { order best: :desc }

  belongs_to :user
  belongs_to :question, touch: true

  validates :user_id, :question_id, :content, presence: true

  after_commit :send_subscription, on: :create, if: -> { question.subscriptions.exists? }

  def choose_as_best
    transaction do
      self.question.answers.update_all(best: false)
      self.update!(best: true)
    end
  end

  private

  def send_subscription
    SubscriptionQuestionJob.perform_later(question, self)
  end
end

app/controllers/answers_controller.rb
# == Schema Information
#
# Table name: answers
#
#  id          :integer          not null, primary key
#  question_id :integer          not null
#  content     :text             not null
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  user_id     :integer
#  best        :boolean          default(FALSE), not null
#

class AnswersController < ApplicationController
  before_action :authenticate_user!
  before_action :build_answer, only: :create

  after_action :publish_answer, only: :create

  load_and_authorize_resource

  include Voted

  respond_to :json, only: [:create, :destroy]
  respond_to :js, only: :update

  def create
    respond_with @answer
  end

  def update
    @answer.update(answer_params)
    respond_with @answer
  end

  def destroy
    respond_with(@answer.destroy, location: question_path(@answer.question))
  end

  def best
    @answer.choose_as_best
  end

  private

  def build_answer
    @question = Question.find(params[:question_id])
    @answer = current_user.answers.create(answer_params.merge(question: @question))
  end

  def publish_answer
    if @answer.valid?
      PrivatePub.publish_to "/questions/#{@question.id}/answers", JSON.parse_nil(render_to_string 'show.json')
    end
  end

  def answer_params
    params.require(:answer).permit(:content, attachments_attributes: [:id, :file, :_destroy])
  end
end

app/controllers/api/v1/answers_controller.rb
class Api::V1::AnswersController < Api::V1::BaseController
  before_action :set_question

  load_and_authorize_resource

  skip_load_resource only: :create

  def index
    respond_with @question.answers
  end

  def show
    respond_with @answer
  end

  def create
    respond_with current_resource_owner.answers.create(answer_params.merge(question: @question))
  end

  private

  def set_question
    @question = Question.find(params[:question_id])
  end

  def answer_params
    params.require(:answer).permit(:content)
  end
end

app/views/answers/_actions.html.haml
.actions
  - if can? :update, answer
    = button_tag 'Edit', class: 'button button_orange button_answer-edit', type: 'button'
  - if can? :destroy, answer
    = link_to 'Delete', answer_path(answer), method: :delete, remote: true, data: { type: :json }, class: 'button button_red button_answer-delete'
  - if can? :best, answer
    = link_to 'Best answer', best_answer_path(answer), method: :patch, remote: true, class: 'button button_green'

app/views/answers/_answer.html.haml
- cache [answer, current_user] do
  - if answer.persisted?
    = content_tag_for :div, answer, class: answer.best ? 'answer_best' : nil do
      = vote_for answer
      %p<= answer.content
      = render answer.attachments
      .comments
        = render answer.comments
      = render partial: 'comments/form', locals: { commentable: answer }
      = render partial: 'answers/edit_form', locals: { answer: answer }
      = render partial: 'answers/actions', locals: { answer: answer }

app/views/answers/_edit_form.html.haml
- if can? :update, answer
  = form_for answer, remote: true, html: { class: 'form', style: 'display: none;' } do |f|
    .form__field
      = f.label :content
      = f.text_area :content, id: nil, class: 'form__input'
    = f.fields_for :attachments do |attachment|
      = render 'layouts/attachment_fields', f: attachment
    .actions
      = f.submit 'Update', class: 'button button_green'

app/views/answers/best.js.erb
(function() {
    $('.answers').html('<%= j render @answer.question.answers %>');
})();

app/views/answers/update.js.erb
(function() {
    <% if @answer.errors.present? %>
        $('form#edit_answer_<%= @answer.id %>').replaceWith('<%= j render partial: 'answers/edit_form', locals: { answer: @answer } %>');
        $('form#edit_answer_<%= @answer.id %>').show();
    <% else %>
        $('#answer_<%= @answer.id %>').replaceWith('<%= j render @answer %>');
    <% end %>
})();