config/routes.rb
Rails.application.routes.draw do
  use_doorkeeper

  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }

  root 'questions#index'

  concern :votable do
    member do
      patch :like
      patch :dislike
      delete :indifferent
    end
  end

  concern :commentable do
    resources :comments, only: :create
  end

  resources :questions, except: :index, concerns: [:votable, :commentable], shallow: true do
    resources :answers, only: [:create, :update, :destroy], concerns: [:votable, :commentable] do
      patch :best, on: :member
    end

    resources :subscriptions, only: [:create, :destroy]
  end

  resources :authorizations, only: [:new, :create] do
    get 'confirm/:token', action: :confirm, on: :member, as: :confirm
  end

  get '/search' => 'search#index', as: :search

  namespace :api do
    namespace :v1 do
      resources :profiles, only: :index do
        get :me, on: :collection
      end

      resources :questions, only: [:index, :show, :create] do
        resources :answers, only: [:index, :show, :create]
      end
    end
  end
end

app/views/layouts/_attachment_fields.html.haml
.nested-fields
  - if f.object.persisted?
    = f.object.file.identifier
    = f.check_box :_destroy, id: "delete_attachment_#{f.object.id}"
    = f.label :_destroy, :delete
  - else
    = f.label :file
    = f.file_field :file
    = link_to_remove_association 'Remove', f, class: 'button button_red'

app/views/layouts/_errors.html.haml
- errors.full_messages.each do |message|
  %span.validation-error
    = j message

app/views/layouts/_flash.html.haml
- flash.each do |name, message|
  = content_tag :div, message, class: "flash flash_#{name}"

app/views/layouts/_navigation.html.haml
%nav.navigation
  = link_to 'Home page', root_path, class: 'button button_blue'
  = link_to 'Add new question', new_question_path, class: 'button button_green'
  - if user_signed_in?
    = link_to 'Sign out', destroy_user_session_path, method: :delete, rel: 'nofollow', class: 'button button_orange'
  - else
    = link_to 'Sign in', new_user_session_path, rel: 'nofollow', class: 'button button_blue'

app/views/layouts/_notifications.js.erb
(function() {
    $('.flash').remove();
    $('.navigation').after('<%= j render 'layouts/flash' %>');
})();

app/views/layouts/_search.html.haml
.search
  = form_tag search_path, method: :get, enforce_utf8: false, id: 'search', class: 'form' do
    .form__field
      = text_field_tag :query, nil, id: 'search_query', class: 'form__input', placeholder: 'Enter search...'
    .form__field
      = select_search_scope
    .actions
      = button_tag 'Search', type: 'submit', name: nil, class: 'button button_green'

app/views/layouts/_vote.html.haml
- if can? :vote, votable
  = link_to 'Like', [:like, votable], remote: true, method: :patch, class: 'voice voice_like', style: "#{'display: none;' if cannot? :like, votable}"
  = link_to 'Dislike', [:dislike, votable], remote: true, method: :patch, class: 'voice voice_dislike', style: "#{'display: none;' if cannot? :dislike, votable}"
  = link_to 'Indifferent', [:indifferent, votable], remote: true, method: :delete, class: 'voice voice_indifferent', style: "#{'display: none;' if cannot? :indifferent, votable}"
Rating:&nbsp;
%span.rating<= votable.rating

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title BettSol
    = include_gon init: true
    = stylesheet_link_tag 'application', media: 'all'
    = javascript_include_tag 'application'
    = csrf_meta_tags
  %body
    = render 'layouts/navigation'
    = render 'layouts/flash'
    = yield